services:
  zed-api:
    image: ghcr.io/ginger21/zed-api:latest
    container_name: zed-api
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - AUTH_PORT=8002
      - TZ=Asia/Shanghai
    volumes:
      - ./accounts.json:/app/accounts.json
      - ./active_account.txt:/app/active_account.txt
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - common-network

networks:
  common-network:
    external: true
